-- Oracle remediation script generated by db_bad_clust
-- Generated at: 2026-08-19T23:28:06Z
-- Review before executing. Dangerous statements are commented out.

-- Summary
--   missing_pk: 23
--   stale_statistics: 23
--   number_as_text: 18
--   date_as_text: 12
--   bad_boolean: 10
--   reserved_words: 5
--   polymorphic: 4
--   wrong_data_types: 4
--   giant_table: 3
--   inconsistent_naming: 3
--   implicit_fk: 2
--   oversized_varchar: 2
--   redundant_index: 2
--   self_referencing: 1
--   eav: 1
--   obsolete_type: 1

-- ============================================================
-- Table: AUDITORIA_LOG
-- ============================================================
-- Review data cleanliness before changing FECHA to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE AUDITORIA_LOG MODIFY (FECHA DATE);

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE AUDITORIA_LOG ADD CONSTRAINT PK_AUDITORIA_LOG PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'AUDITORIA_LOG');

-- ============================================================
-- Table: BACKUP_DATOS
-- ============================================================
-- Manual refactor required.
-- [severity=high, effort=high, impact=low]
-- Giant table BACKUP_DATOS: split into smaller, focused tables.

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE BACKUP_DATOS ADD CONSTRAINT PK_BACKUP_DATOS PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'BACKUP_DATOS');

-- ============================================================
-- Table: CACHE_TEMPORAL
-- ============================================================
-- Column TIMESTAMP is a SQL reserved word.
-- [severity=high, effort=low, impact=medium]
ALTER TABLE CACHE_TEMPORAL RENAME COLUMN "TIMESTAMP" TO TIMESTAMP_COL;

-- Review data cleanliness before changing TIMESTAMP to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE CACHE_TEMPORAL MODIFY ("TIMESTAMP" DATE);

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE CACHE_TEMPORAL ADD CONSTRAINT PK_CACHE_TEMPORAL PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'CACHE_TEMPORAL');

-- ============================================================
-- Table: CATEGORIAS
-- ============================================================
-- Review data cleanliness before changing NIVEL to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE CATEGORIAS MODIFY (NIVEL NUMBER);

-- [severity=medium, effort=low, impact=medium]
ALTER TABLE CATEGORIAS MODIFY (ACTIVO NUMBER(1));
ALTER TABLE CATEGORIAS ADD CONSTRAINT CATEGORIAS_CHK_ACTIVO CHECK (ACTIVO IN (0, 1));

-- Manual review required.
-- [severity=medium, effort=medium, impact=low]
-- Self-referencing column CAT_PADRE_ID in CATEGORIAS: verify hierarchy intent.

-- Guessed target type NUMBER from column name; validate data first.
-- [severity=medium, effort=medium, impact=medium]
ALTER TABLE CATEGORIAS MODIFY (ACTIVO NUMBER);

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE CATEGORIAS ADD CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'CATEGORIAS');

-- ============================================================
-- Table: CLIENTES_DIRECCIONES
-- ============================================================
-- Manual rename campaign required.
-- [severity=low, effort=high, impact=low]
-- Table CLIENTES_DIRECCIONES has inconsistent naming; standardize columns.

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE CLIENTES_DIRECCIONES ADD CONSTRAINT PK_CLIENTES_DIRECCIONES PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'CLIENTES_DIRECCIONES');

-- ============================================================
-- Table: CONFIGURACION
-- ============================================================
-- Review data cleanliness before changing VALOR to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE CONFIGURACION MODIFY (VALOR NUMBER);

-- [severity=medium, effort=low, impact=medium]
ALTER TABLE CONFIGURACION MODIFY (ACTIVO NUMBER(1));
ALTER TABLE CONFIGURACION ADD CONSTRAINT CONFIGURACION_CHK_ACTIVO CHECK (ACTIVO IN (0, 1));

-- Manual refactor required.
-- [severity=medium, effort=high, impact=low]
-- Polymorphic table CONFIGURACION: split into one table per type or add per-type FKs.

-- Manual refactor required.
-- [severity=high, effort=high, impact=low]
-- EAV table CONFIGURACION: normalize to relational columns or use JSON/XML.

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE CONFIGURACION ADD CONSTRAINT PK_CONFIGURACION PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'CONFIGURACION');

-- ============================================================
-- Table: DATOS_MAESTROS
-- ============================================================
-- [severity=medium, effort=low, impact=medium]
ALTER TABLE DATOS_MAESTROS MODIFY (FLAG_ACTIVO NUMBER(1));
ALTER TABLE DATOS_MAESTROS ADD CONSTRAINT DATOS_MAESTROS_CHK_FLAG_ACTIVO CHECK (FLAG_ACTIVO IN (0, 1));

-- Guessed target type NUMBER from column name; validate data first.
-- [severity=medium, effort=medium, impact=medium]
ALTER TABLE DATOS_MAESTROS MODIFY (FLAG_ACTIVO NUMBER);

-- Convert deprecated RAW to BLOB.
-- [severity=high, effort=low, impact=medium]
ALTER TABLE DATOS_MAESTROS MODIFY (CODIGO_HEX BLOB);

-- Suggested size 100; validate actual data length first.
-- [severity=low, effort=low, impact=medium]
ALTER TABLE DATOS_MAESTROS MODIFY (FLAG_ACTIVO VARCHAR2(100));

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE DATOS_MAESTROS ADD CONSTRAINT PK_DATOS_MAESTROS PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'DATOS_MAESTROS');

-- ============================================================
-- Table: DEPARTAMENTOS
-- ============================================================
-- Review data cleanliness before changing PRESUPUESTO to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE DEPARTAMENTOS MODIFY (PRESUPUESTO NUMBER);

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'DEPARTAMENTOS');

-- ============================================================
-- Table: EMPLEADOS
-- ============================================================
-- Review data cleanliness before changing FECHA_ALTA to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE EMPLEADOS MODIFY (FECHA_ALTA DATE);

-- Review data cleanliness before changing FECHA_NACIMIENTO to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE EMPLEADOS MODIFY (FECHA_NACIMIENTO DATE);

-- Review data cleanliness before changing SALARIO to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE EMPLEADOS MODIFY (SALARIO NUMBER);

-- [severity=medium, effort=low, impact=medium]
ALTER TABLE EMPLEADOS MODIFY (ACTIVO NUMBER(1));
ALTER TABLE EMPLEADOS ADD CONSTRAINT EMPLEADOS_CHK_ACTIVO CHECK (ACTIVO IN (0, 1));

-- Guessed target type NUMBER from column name; validate data first.
-- [severity=high, effort=medium, impact=medium]
ALTER TABLE EMPLEADOS MODIFY (ACTIVO NUMBER);

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY (ID);

-- Keep the composite index instead.
-- [severity=medium, effort=low, impact=low]
DROP INDEX IDX_EMPLEADOS_0;

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'EMPLEADOS');

-- ============================================================
-- Table: EMPLEADOS_HISTORIAL
-- ============================================================
-- Review data cleanliness before changing FECHA_CAMBIO to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE EMPLEADOS_HISTORIAL MODIFY (FECHA_CAMBIO DATE);

-- Review data cleanliness before changing SALARIO_ANTERIOR to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE EMPLEADOS_HISTORIAL MODIFY (SALARIO_ANTERIOR NUMBER);

-- Review data cleanliness before changing SALARIO_NUEVO to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE EMPLEADOS_HISTORIAL MODIFY (SALARIO_NUEVO NUMBER);

-- Manual reference resolution required.
-- [severity=medium, effort=medium, impact=low]
-- Implicit FK EMPLEADO_ID in EMPLEADOS_HISTORIAL: add FOREIGN KEY referencing target table.

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE EMPLEADOS_HISTORIAL ADD CONSTRAINT PK_EMPLEADOS_HISTORIAL PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'EMPLEADOS_HISTORIAL');

-- ============================================================
-- Table: INVENTARIO
-- ============================================================
-- Review data cleanliness before changing FECHA_ACTUALIZACION to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE INVENTARIO MODIFY (FECHA_ACTUALIZACION DATE);

-- Review data cleanliness before changing STOCK_2 to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE INVENTARIO MODIFY (STOCK_2 NUMBER);

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE INVENTARIO ADD CONSTRAINT PK_INVENTARIO PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'INVENTARIO');

-- ============================================================
-- Table: METADATA
-- ============================================================
-- Manual refactor required.
-- [severity=medium, effort=high, impact=low]
-- Polymorphic table METADATA: split into one table per type or add per-type FKs.

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE METADATA ADD CONSTRAINT PK_METADATA PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'METADATA');

-- ============================================================
-- Table: ORDENES_COMPRA
-- ============================================================
-- Review data cleanliness before changing FECHA_ORDEN to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE ORDENES_COMPRA MODIFY (FECHA_ORDEN DATE);

-- Review data cleanliness before changing CANTIDAD to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE ORDENES_COMPRA MODIFY (CANTIDAD NUMBER);

-- Review data cleanliness before changing FECHA_ORDEN to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE ORDENES_COMPRA MODIFY (FECHA_ORDEN NUMBER);

-- Review data cleanliness before changing PRECIO to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE ORDENES_COMPRA MODIFY (PRECIO NUMBER);

-- Manual rename campaign required.
-- [severity=low, effort=high, impact=low]
-- Table ORDENES_COMPRA has inconsistent naming; standardize columns.

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE ORDENES_COMPRA ADD CONSTRAINT PK_ORDENES_COMPRA PRIMARY KEY (ID);

-- Keep the composite index instead.
-- [severity=medium, effort=low, impact=low]
DROP INDEX IDX_ORDENES_COMPRA_0;

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'ORDENES_COMPRA');

-- ============================================================
-- Table: PRODUCTOS
-- ============================================================
-- Review data cleanliness before changing PRECIOS to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE PRODUCTOS MODIFY (PRECIOS NUMBER);

-- Review data cleanliness before changing PROVEEDORES_ID to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE PRODUCTOS MODIFY (PROVEEDORES_ID NUMBER);

-- Review data cleanliness before changing STOCK_SEGURIDAD to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE PRODUCTOS MODIFY (STOCK_SEGURIDAD NUMBER);

-- Manual reference resolution required.
-- [severity=medium, effort=medium, impact=low]
-- Implicit FK PROVEEDORES_ID in PRODUCTOS: add FOREIGN KEY referencing target table.

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'PRODUCTOS');

-- ============================================================
-- Table: PROVEEDORES
-- ============================================================
-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE PROVEEDORES ADD CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'PROVEEDORES');

-- ============================================================
-- Table: REPORTES
-- ============================================================
-- Column FROM is a SQL reserved word.
-- [severity=high, effort=low, impact=medium]
ALTER TABLE REPORTES RENAME COLUMN "FROM" TO FROM_COL;

-- Column NULL is a SQL reserved word.
-- [severity=high, effort=low, impact=medium]
ALTER TABLE REPORTES RENAME COLUMN "NULL" TO NULL_COL;

-- Column SELECT is a SQL reserved word.
-- [severity=high, effort=low, impact=medium]
ALTER TABLE REPORTES RENAME COLUMN "SELECT" TO SELECT_COL;

-- Column WHERE is a SQL reserved word.
-- [severity=high, effort=low, impact=medium]
ALTER TABLE REPORTES RENAME COLUMN "WHERE" TO WHERE_COL;

-- Review data cleanliness before changing FECHA_GENERACION to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE REPORTES MODIFY (FECHA_GENERACION DATE);

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE REPORTES ADD CONSTRAINT PK_REPORTES PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'REPORTES');

-- ============================================================
-- Table: TABLA_BASE_DATOS
-- ============================================================
-- Manual refactor required.
-- [severity=high, effort=high, impact=low]
-- Giant table TABLA_BASE_DATOS: split into smaller, focused tables.

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE TABLA_BASE_DATOS ADD CONSTRAINT PK_TABLA_BASE_DATOS PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'TABLA_BASE_DATOS');

-- ============================================================
-- Table: TABLA_VACIA
-- ============================================================
-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE TABLA_VACIA ADD CONSTRAINT PK_TABLA_VACIA PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'TABLA_VACIA');

-- ============================================================
-- Table: TBL_DATOS
-- ============================================================
-- Manual rename campaign required.
-- [severity=low, effort=high, impact=low]
-- Table TBL_DATOS has inconsistent naming; standardize columns.

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE TBL_DATOS ADD CONSTRAINT PK_TBL_DATOS PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'TBL_DATOS');

-- ============================================================
-- Table: TODO_EN_UNO
-- ============================================================
-- Review data cleanliness before changing FECHA_O_DIRECCION to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE TODO_EN_UNO MODIFY (FECHA_O_DIRECCION DATE);

-- Review data cleanliness before changing CANT_O_PRECIO to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE TODO_EN_UNO MODIFY (CANT_O_PRECIO NUMBER);

-- [severity=medium, effort=low, impact=medium]
ALTER TABLE TODO_EN_UNO MODIFY (ESTADO_O_ACTIVO NUMBER(1));
ALTER TABLE TODO_EN_UNO ADD CONSTRAINT TODO_EN_UNO_CHK_ESTADO_O_ACTIV CHECK (ESTADO_O_ACTIVO IN (0, 1));

-- [severity=medium, effort=low, impact=medium]
ALTER TABLE TODO_EN_UNO MODIFY (FLAG_1_0 NUMBER(1));
ALTER TABLE TODO_EN_UNO ADD CONSTRAINT TODO_EN_UNO_CHK_FLAG_1_0 CHECK (FLAG_1_0 IN (0, 1));

-- [severity=medium, effort=low, impact=medium]
ALTER TABLE TODO_EN_UNO MODIFY (FLAG_S_N NUMBER(1));
ALTER TABLE TODO_EN_UNO ADD CONSTRAINT TODO_EN_UNO_CHK_FLAG_S_N CHECK (FLAG_S_N IN (0, 1));

-- [severity=medium, effort=low, impact=medium]
ALTER TABLE TODO_EN_UNO MODIFY (FLAG_T_F NUMBER(1));
ALTER TABLE TODO_EN_UNO ADD CONSTRAINT TODO_EN_UNO_CHK_FLAG_T_F CHECK (FLAG_T_F IN (0, 1));

-- [severity=medium, effort=low, impact=medium]
ALTER TABLE TODO_EN_UNO MODIFY (FLAG_Y_N NUMBER(1));
ALTER TABLE TODO_EN_UNO ADD CONSTRAINT TODO_EN_UNO_CHK_FLAG_Y_N CHECK (FLAG_Y_N IN (0, 1));

-- Manual refactor required.
-- [severity=medium, effort=high, impact=low]
-- Polymorphic table TODO_EN_UNO: split into one table per type or add per-type FKs.

-- Manual refactor required.
-- [severity=medium, effort=high, impact=low]
-- Giant table TODO_EN_UNO: split into smaller, focused tables.

-- Suggested size 100; validate actual data length first.
-- [severity=low, effort=low, impact=medium]
ALTER TABLE TODO_EN_UNO MODIFY (ESTADO_O_ACTIVO VARCHAR2(100));

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE TODO_EN_UNO ADD CONSTRAINT PK_TODO_EN_UNO PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'TODO_EN_UNO');

-- ============================================================
-- Table: TRANSACCIONES
-- ============================================================
-- Review data cleanliness before changing FECHA to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE TRANSACCIONES MODIFY (FECHA DATE);

-- Review data cleanliness before changing MONTO to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE TRANSACCIONES MODIFY (MONTO NUMBER);

-- Manual refactor required.
-- [severity=medium, effort=high, impact=low]
-- Polymorphic table TRANSACCIONES: split into one table per type or add per-type FKs.

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE TRANSACCIONES ADD CONSTRAINT PK_TRANSACCIONES PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'TRANSACCIONES');

-- ============================================================
-- Table: USUARIOS_WEB
-- ============================================================
-- Review data cleanliness before changing FECHA_EXPIRACION to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE USUARIOS_WEB MODIFY (FECHA_EXPIRACION DATE);

-- Review data cleanliness before changing INTENTOS_FALLIDOS to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE USUARIOS_WEB MODIFY (INTENTOS_FALLIDOS NUMBER);

-- [severity=medium, effort=low, impact=medium]
ALTER TABLE USUARIOS_WEB MODIFY (ACTIVO NUMBER(1));
ALTER TABLE USUARIOS_WEB ADD CONSTRAINT USUARIOS_WEB_CHK_ACTIVO CHECK (ACTIVO IN (0, 1));

-- Guessed target type NUMBER from column name; validate data first.
-- [severity=medium, effort=medium, impact=medium]
ALTER TABLE USUARIOS_WEB MODIFY (ACTIVO NUMBER);

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE USUARIOS_WEB ADD CONSTRAINT PK_USUARIOS_WEB PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'USUARIOS_WEB');

-- ============================================================
-- Table: VENTAS
-- ============================================================
-- Review data cleanliness before changing FECHA_VENTA to DATE.
-- [severity=high, effort=low, impact=low]
ALTER TABLE VENTAS MODIFY (FECHA_VENTA DATE);

-- Review data cleanliness before changing PRECIO_TOTAL to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE VENTAS MODIFY (PRECIO_TOTAL NUMBER);

-- Review data cleanliness before changing PRODUCTO_FK to NUMBER.
-- [severity=high, effort=low, impact=low]
ALTER TABLE VENTAS MODIFY (PRODUCTO_FK NUMBER);

-- Verify ID is unique and not nullable before enabling.
-- [severity=high, effort=medium, impact=high]
ALTER TABLE VENTAS ADD CONSTRAINT PK_VENTAS PRIMARY KEY (ID);

-- [severity=medium, effort=low, impact=high]
EXEC DBMS_STATS.GATHER_TABLE_STATS(ownname => USER, tabname => 'VENTAS');
