"""
evaluator.py — Clustering quality evaluation

Purpose:
  Evaluate the quality of clusters generated by ClusterEngine
  using internal metrics (silhouette, Davies-Bouldin, etc.) and
  cross-analysis against tables and known anti-patterns.

Metrics:
  - Silhouette Score: intra-cluster cohesion vs inter-cluster separation
  - Davies-Bouldin Index: average similarity between clusters (lower = better)
  - Calinski-Harabasz Index: inter/intra variance ratio (higher = better)
  - Cross-table analysis: table purity within clusters
  - Anti-pattern composition: which anti-patterns appear in each cluster
  - External validation (ARI, NMI): agreement with ground truth labels

Usage:
  evaluator = Evaluator()
  metrics = evaluator.evaluate(X_reduced, labels)
  report = evaluator.print_report(schema, labels, metrics)
"""

from __future__ import annotations

import logging
from collections import Counter, defaultdict
from typing import Any

import numpy as np
from exceptions import EvaluationError

logger = logging.getLogger(__name__)


class Evaluator:
    """Evaluates clustering quality and generates reports."""

    # ── Internal metrics ────────────────────────────────────────────────

    @staticmethod
    def silhouette(X: np.ndarray, labels: np.ndarray) -> float:
        """Silhouette Score (-1 to 1, higher = better)."""
        from sklearn.metrics import silhouette_score

        unique = set(labels)
        if len(unique) <= 1 or len(unique) >= X.shape[0]:
            return 0.0
        try:
            try:
                return float(silhouette_score(X, labels))
            except Exception as exc:
                raise EvaluationError("Silhouette calculation failed") from exc
        except EvaluationError as e:
            logger.warning("Error computing silhouette: %s", e)
            return 0.0

    @staticmethod
    def davies_bouldin(X: np.ndarray, labels: np.ndarray) -> float:
        """Davies-Bouldin Index (0 to inf, lower = better)."""
        from sklearn.metrics import davies_bouldin_score

        unique = set(labels) - {-1}
        if len(unique) <= 1:
            return 0.0
        try:
            try:
                return float(davies_bouldin_score(X, labels))
            except Exception as exc:
                raise EvaluationError("Davies-Bouldin calculation failed") from exc
        except EvaluationError as e:
            logger.warning("Error computing Davies-Bouldin: %s", e)
            return 0.0

    @staticmethod
    def calinski_harabasz(X: np.ndarray, labels: np.ndarray) -> float:
        """Calinski-Harabasz Index (higher = better)."""
        from sklearn.metrics import calinski_harabasz_score

        unique = set(labels) - {-1}
        if len(unique) <= 1:
            return 0.0
        try:
            try:
                return float(calinski_harabasz_score(X, labels))
            except Exception as exc:
                raise EvaluationError("Calinski-Harabasz calculation failed") from exc
        except EvaluationError as e:
            logger.warning("Error computing CH: %s", e)
            return 0.0

    # ── External validation (ground truth) ──────────────────────────────

    @staticmethod
    def adjusted_rand_index(
        labels_pred: np.ndarray,
        labels_true: np.ndarray,
    ) -> float:
        """Adjusted Rand Index (-1 to 1, higher = better agreement)."""
        from sklearn.metrics import adjusted_rand_score

        return float(adjusted_rand_score(labels_true, labels_pred))

    @staticmethod
    def normalized_mutual_info(
        labels_pred: np.ndarray,
        labels_true: np.ndarray,
    ) -> float:
        """Normalized Mutual Information (0 to 1, higher = better)."""
        from sklearn.metrics import normalized_mutual_info_score

        return float(normalized_mutual_info_score(labels_true, labels_pred))

    @staticmethod
    def anomaly_detection_metrics(
        labels_pred: np.ndarray,
        labels_true: np.ndarray,
    ) -> dict[str, float]:
        """Compute anomaly precision/recall/F1 treating -1 as anomaly.

        Compares predicted noise (-1) against columns with unknown
        ground truth (None) as the anomaly class.

        Args:
            labels_pred: Predicted cluster labels (-1 = noise).
            labels_true: Ground truth labels (None = unknown/noise).

        Returns:
            Dict with precision, recall, f1, support.
        """
        from sklearn.metrics import precision_recall_fscore_support

        # Binarize: -1 in pred = anomaly (1), else 0
        # Binarize: None in true = anomaly (1), else 0
        pred_bin: np.ndarray = np.where(labels_pred == -1, 1, 0).astype(int)
        true_bin: np.ndarray = np.where(
            np.array([t is None for t in labels_true]),
            1,
            0,
        ).astype(int)

        if true_bin.sum() == 0:
            return {"precision": 0.0, "recall": 0.0, "f1": 0.0, "support": 0}

        precision, recall, f1, _ = precision_recall_fscore_support(
            true_bin,
            pred_bin,
            average="binary",
            zero_division=0.0,
        )
        support: int = int(true_bin.sum())
        return {
            "precision": float(precision),
            "recall": float(recall),
            "f1": float(f1),
            "support": support,
        }

    @staticmethod
    def centroid_anomaly_scores(
        X: np.ndarray,
        labels: np.ndarray,
        percentile: float = 95.0,
    ) -> dict[str, Any]:
        """Detect structural anomalies via distance to cluster centroid.

        For each point, computes the distance to its cluster centroid.
        Points beyond the given percentile are flagged as structural
        anomalies. Only for methods with centroids (e.g. KMeans).

        Args:
            X: Reduced feature matrix, shape (N, d).
            labels: Cluster assignments (no -1 expected).
            percentile: Distance percentile threshold (default 95).

        Returns:
            Dict with anomaly_indices, anomaly_distances, n_anomalies,
            mean_distance, std_distance.
        """
        unique: np.ndarray = np.unique(labels)
        if len(unique) <= 1 or -1 in unique:
            return {
                "anomaly_indices": np.array([], dtype=int),
                "anomaly_distances": np.array([], dtype=float),
                "n_anomalies": 0,
                "mean_distance": 0.0,
                "std_distance": 0.0,
            }

        centroids: dict[int, np.ndarray] = {}
        for cid in unique:
            mask_c: np.ndarray = labels == cid
            centroids[int(cid)] = X[mask_c].mean(axis=0)

        distances: np.ndarray = np.array([
            float(np.linalg.norm(X[i] - centroids[int(labels[i])]))
            for i in range(X.shape[0])
        ])

        threshold: float = float(np.percentile(distances, percentile))
        anomaly_mask: np.ndarray = distances > threshold
        anomaly_indices: np.ndarray = np.where(anomaly_mask)[0]

        return {
            "anomaly_indices": anomaly_indices,
            "anomaly_distances": distances[anomaly_mask],
            "n_anomalies": int(anomaly_mask.sum()),
            "mean_distance": float(distances.mean()),
            "std_distance": float(distances.std()),
            "threshold": float(threshold),
            "percentile": float(percentile),
        }

    def validate_against_ground_truth(
        self,
        labels_pred: np.ndarray,
        labels_true: list[str | None],
        X: np.ndarray | None = None,
    ) -> dict[str, Any]:
        """External validation: compare predicted clusters against ground truth.

        Args:
            labels_pred: Predicted cluster labels from clustering.
            labels_true: Ground truth anti-pattern labels per column.
            X: Optional reduced feature matrix for centroid anomaly scoring.

        Returns:
            Dict with ari, nmi, n_gt_labels, anomaly metrics, and
            centroid-based structural anomaly scores if X is provided.
        """
        # Filter to columns with known ground truth
        mask: np.ndarray = np.array([t is not None for t in labels_true])
        if mask.sum() < 2:
            return {
                "error": "Less than 2 columns with ground truth labels",
                "ari": 0.0,
                "nmi": 0.0,
                "n_gt_labels": int(mask.sum()),
            }

        pred_known: np.ndarray = labels_pred[mask]
        true_known: np.ndarray = np.array([t for t in labels_true if t is not None])

        ari: float = self.adjusted_rand_index(pred_known, true_known)
        nmi: float = self.normalized_mutual_info(pred_known, true_known)
        anomaly: dict[str, float] = self.anomaly_detection_metrics(labels_pred, labels_true)

        result: dict[str, Any] = {
            "ari": ari,
            "nmi": nmi,
            "n_gt_labels": int(mask.sum()),
            "anomaly_precision": anomaly["precision"],
            "anomaly_recall": anomaly["recall"],
            "anomaly_f1": anomaly["f1"],
            "anomaly_support": anomaly["support"],
        }

        if X is not None and -1 not in set(labels_pred):
            centroid_anomaly: dict[str, Any] = self.centroid_anomaly_scores(X, labels_pred)
            result["structural_anomalies"] = centroid_anomaly["n_anomalies"]
            result["structural_anomaly_ratio"] = (
                centroid_anomaly["n_anomalies"] / X.shape[0]
                if X.shape[0] > 0
                else 0.0
            )
            result["centroid_mean_distance"] = centroid_anomaly["mean_distance"]
            result["centroid_std_distance"] = centroid_anomaly["std_distance"]

        return result

    def evaluate(self, X: np.ndarray, labels: np.ndarray) -> dict[str, Any]:
        """
        Compute all internal metrics.

        Returns:
            Dict with computed metrics.
        """
        mask = labels != -1
        if mask.sum() == 0:
            return {"error": "No samples with assigned cluster"}

        X_clean = X[mask]
        labels_clean = labels[mask]

        return {
            "silhouette": self.silhouette(X_clean, labels_clean),
            "davies_bouldin": self.davies_bouldin(X_clean, labels_clean),
            "calinski_harabasz": self.calinski_harabasz(X_clean, labels_clean),
            "n_clusters": len(set(labels_clean)),
            "n_samples": len(labels),
            "n_noise": int((labels == -1).sum()),
        }

    # ── Cross-table analysis ────────────────────────────────────────────

    @staticmethod
    def cross_table_analysis(
        column_table_map: list[str],
        labels: np.ndarray,
    ) -> dict[str, Any]:
        """
        Analyze how columns from each table are distributed across clusters.

        Args:
            column_table_map: List with table name per column.
            labels: Cluster assignment per column.

        Returns:
            Dict with table -> {cluster_id: count} and purity metrics.
        """
        table_clusters: dict[str, dict[int, int]] = defaultdict(lambda: defaultdict(int))  # type: ignore[arg-type]
        for table_name, label in zip(column_table_map, labels):
            table_clusters[table_name][int(label)] += 1

        # Purity: fraction of a table's columns in their majority cluster
        purity: dict[str, dict[str, Any]] = {}
        for table, clusters in table_clusters.items():
            total = sum(clusters.values())
            majority = max(clusters.values())
            purity[table] = {
                "total_columns": total,
                "majority_cluster": max(clusters, key=clusters.get),
                "majority_count": majority,
                "purity": majority / total if total > 0 else 0.0,
                "cluster_distribution": dict(clusters),
            }

        purity_values = [p["purity"] for p in purity.values()]
        avg_purity = np.mean(purity_values) if purity_values else 0.0

        return {
            "table_distribution": dict(table_clusters),
            "table_purity": purity,
            "average_purity": float(avg_purity),
        }

    # ── Anti-pattern composition per cluster ────────────────────────────

    @staticmethod
    def cluster_composition(
        labels: np.ndarray,
        column_metadata: list[Any],
    ) -> dict[int, dict[str, Any]]:
        """
        Analyze which anti-pattern characteristics appear in each cluster.

        Args:
            labels: Cluster assignment per column.
            column_metadata: List of ColumnMetadata objects.

        Returns:
            Dict with cluster_id -> {composition metrics}.
        """
        from schema_extractor import ColumnMetadata  # noqa: F401  # used for type info

        clusters: dict[int, list[Any]] = defaultdict(list)
        for label, col in zip(labels, column_metadata):
            clusters[int(label)].append(col)

        composition: dict[int, dict[str, Any]] = {}
        for cluster_id, cols in clusters.items():
            total = len(cols)
            _ = sum(1 for c in cols if not c.is_primary_key and c.name.upper() in ("ID",))

            null_count = sum(1 for c in cols if c.nullable)
            text_types = sum(1 for c in cols if c.data_type.upper().startswith("VARCHAR"))
            numeric_types = sum(
                1 for c in cols if c.data_type.upper() in ("NUMBER", "FLOAT", "INTEGER", "INT")
            )

            composition[int(cluster_id)] = {
                "total_columns": total,
                "pct_nullable": null_count / total * 100 if total else 0,
                "pct_varchar": text_types / total * 100 if total else 0,
                "pct_numeric": numeric_types / total * 100 if total else 0,
                "types_distribution": dict(Counter(c.data_type for c in cols)),
            }

        return composition

    # ── Report ──────────────────────────────────────────────────────────

    @staticmethod
    def print_report(
        metrics: dict[str, Any],
        cross_table: dict[str, Any] | None = None,
        composition: dict[int, dict[str, Any]] | None = None,
    ) -> str:
        """
        Generate a formatted text report with all results.

        Returns:
            Multi-line string report.
        """
        lines: list[str] = []
        lines.append("=" * 60)
        lines.append("EVALUACION DE CLUSTERING")
        lines.append("=" * 60)

        if "error" in metrics:
            lines.append(f"ERROR: {metrics['error']}")
            return "\n".join(lines)

        lines.append("\n--- Metricas Internas ---")
        lines.append(f"  Silhouette Score:         {metrics['silhouette']:.4f}")
        lines.append(f"  Davies-Bouldin Index:     {metrics['davies_bouldin']:.4f}")
        lines.append(f"  Calinski-Harabasz Index:  {metrics['calinski_harabasz']:.2f}")
        lines.append(f"  Clusters formados:        {metrics['n_clusters']}")
        lines.append(f"  Muestras totales:         {metrics['n_samples']}")
        lines.append(f"  Outliers (DBSCAN):        {metrics['n_noise']}")

        if cross_table:
            lines.append("\n--- Distribucion por Tabla ---")
            lines.append(f"  Pureza promedio: {cross_table['average_purity']:.2%}")
            for table, info in sorted(cross_table.get("table_purity", {}).items()):
                lines.append(
                    f"  {table}: pureza={info['purity']:.0%} "
                    f"({info['total_columns']} cols, cluster mayoritario #{info['majority_cluster']})"
                )

        if composition:
            lines.append("\n--- Composicion por Cluster ---")
            for cid, info in sorted(composition.items()):
                if cid == -1:
                    continue
                lines.append(f"  Cluster #{cid}: {info['total_columns']} columnas")
                lines.append(f"    Nullable: {info['pct_nullable']:.0f}%")
                lines.append(f"    VARCHAR:  {info['pct_varchar']:.0f}%")
                lines.append(f"    Numerico: {info['pct_numeric']:.0f}%")

        lines.append("\n" + "=" * 60)
        return "\n".join(lines)

    @staticmethod
    def print_validation_report(validation: dict[str, Any]) -> str:
        """Generate a formatted report for ground truth validation.

        Args:
            validation: Dict from validate_against_ground_truth().

        Returns:
            Multi-line string report.
        """
        lines: list[str] = []
        lines.append("-" * 50)
        lines.append("VALIDACION H1 — Ground Truth")
        lines.append("-" * 50)

        if "error" in validation:
            lines.append(f"  ERROR: {validation['error']}")
            lines.append(f"  Columnas con GT: {validation.get('n_gt_labels', 0)}")
        else:
            lines.append(f"  Adjusted Rand Index (ARI):  {validation['ari']:.4f}")
            lines.append(f"  Normalized Mutual Info:    {validation['nmi']:.4f}")
            lines.append(f"  Columnas con GT:           {validation['n_gt_labels']}")
            lines.append("  Anomaly (noise) detection:")
            lines.append(f"    Precision: {validation['anomaly_precision']:.2%}")
            lines.append(f"    Recall:    {validation['anomaly_recall']:.2%}")
            lines.append(f"    F1:        {validation['anomaly_f1']:.2%}")
            lines.append(f"    Support:   {validation['anomaly_support']}")
            if "structural_anomalies" in validation:
                lines.append("  Structural anomalies (centroid distance):")
                lines.append(f"    Count:  {validation['structural_anomalies']}")
                lines.append(f"    Ratio:  {validation['structural_anomaly_ratio']:.2%}")
                lines.append(f"    Mean distance: {validation['centroid_mean_distance']:.4f}")
                lines.append(f"    Std distance:  {validation['centroid_std_distance']:.4f}")

        lines.append("-" * 50)
        return "\n".join(lines)
